name: up2date
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter_bloc: ^8.1.3
  google_sign_in: ^6.1.4
  http: ^1.0.0
  carousel_slider: ^4.2.1
  json_serializable: ^6.7.0
  url_launcher: ^6.1.11
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  hive_generator: ^2.0.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - lib/images/