// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRL4d6FmgJCpwQHstntdgq8XhF6-9_exY',
    appId: '1:586494701595:web:e86ab122d7ce333b4c48be',
    messagingSenderId: '586494701595',
    projectId: 'up2date-4d6a9',
    authDomain: 'up2date-4d6a9.firebaseapp.com',
    storageBucket: 'up2date-4d6a9.appspot.com',
    measurementId: 'G-L9DP20YJHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFiRVX9pXAarTAPqbdzsx5KyROGt7gmXo',
    appId: '1:586494701595:android:6d115525552abfa04c48be',
    messagingSenderId: '586494701595',
    projectId: 'up2date-4d6a9',
    storageBucket: 'up2date-4d6a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAymvPlyPNDVbBxFpKozStrP9ZeCQuXZqE',
    appId: '1:586494701595:ios:1c9a3c979ecb16ff4c48be',
    messagingSenderId: '586494701595',
    projectId: 'up2date-4d6a9',
    storageBucket: 'up2date-4d6a9.appspot.com',
    iosClientId: '586494701595-4tlosennp91vri0cl3k2rvoeussfbf8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.up2date',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAymvPlyPNDVbBxFpKozStrP9ZeCQuXZqE',
    appId: '1:586494701595:ios:e69c24cc2822a1cb4c48be',
    messagingSenderId: '586494701595',
    projectId: 'up2date-4d6a9',
    storageBucket: 'up2date-4d6a9.appspot.com',
    iosClientId: '586494701595-f4f7cgv2598aivvl4ed63uqie1j71dfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.up2date.RunnerTests',
  );
}
